title: Rush Text Generator
description: Generate text using iconic Rush fonts
baseurl: "/rush-text"
url: "https://cseeman.github.io"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md