title: Rush Text Generator
description: Generate text using iconic Rush fonts
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md